### PR TITLE
Run unit tests in CircleCI

### LINKED ISSUE #15: Execute unit tests in CircleCI
The current sqlite-based unit tests should be run in CircleCI.

### LINKED ISSUE #16: Document CircleCI setup and github integration
The developer docs as of #1 have information on how our github is set up, including the integration with magic files. We should have the same for CircleCI--not a duplication of CircleCI docs, just how we have it set up.

### PR DESCRIPTION
**Pull request by jtniehof**
This PR sets up unit testing in CircleCI.

It documents the basic CircleCI/GitHub setup, for configuration which isn't in the .yaml (Closes #16).

It splits the build and the tests into separate jobs: the build which installs most dependencies and dbprocessing itself, the postgres test which installs the necessary postgres tools and creates the postgres db, and the unittest job which runs the unit tests (Closes #15). It uses workspace persistence to carry .local across (which catches all the Python installs, basically.)

It also clears out a few things we aren't currently using:

- It doesn't install vim, since it would need to do that for every job, slowing things down. vim can be installed from the command line after ssh in if something needs to be debugged.
- It removes the environment variable setting for pip virtualenv handling, since we aren't using virtualenv. Might be a nice thing to look into, particularly once caching can be set up.

This doesn't do any caching at this point...I wanted to get the basic setup running. But in the future some level of caching the pip installs might be useful.

Draft for now until I can be sure the tests actually work....

## PR Checklist

- [X] Pull request has descriptive title
- [X] Pull request gives overview of changes
- [X] (N/A) New code has inline comments where necessary
- [X] (N/A) Any new modules, functions or classes have docstrings consistent with dbprocessing style
- [X] (N/A) Major new functionality has appropriate Sphinx documentation
- [X] (N/A) Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [X] (N/A) New features and bug fixes should have unit tests
- [X] Relevant issues are linked in the description (e.g. `See issue #` or `Closes #`)

### CODE REVIEW

**Comment by jtniehof** [comment]
Once this is merged I'll update the checks to explicitly require the unittest and postgres jobs to succeed in order to merge, but until this is merged that would block any other merges :)

**Comment by jtniehof** [comment]
CircleCI reports out both the succes of the entire workflow, and the success of each individual job. Right now I have both workflow and the "build" job required in order to merge ("build" because that was the only job in the initial setup.) Reasonable options would be:

1. Just the workflow success is required. This is the same as requiring all the jobs, since the workflow only succeeds if all jobs succeed. I'm leaning in this direction, since it requires the fewest number of things to work in the communication from CircleCI to GitHub.
2. Each individual job is required, but not the workflow.
3. The workflow and each job are required.

Regardless of what is _required_ all get reported out in the PR, so you can see which job failed if the workflow failed.  You can see above that "4 successful checks" are listed, and only the workflow (main) and the build job have the "required" tag.

**Review by dnadeau-lanl — APPROVED** [review]
Thanks for this!  I am very happy to see your tests running successfully in circleci!

**Comment by jtniehof** [comment]
Thanks. I set up the master branch protection rule to require the workflow to pass and not care about individual jobs. (I also set up a default branch protection rule to make it really hard to push to other branches, since PRs should normally be submitted from forks...we can revisit that later.)

**Pull request merged**
